# Generated by Django 4.1 on 2024-03-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcApp', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
    ]
